"""add order_number, razorpay_order_id, payment_method

Revision ID: 746870186368
Revises: dc9594c408b0
Create Date: 2025-08-28 21:29:25.808769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746870186368'
down_revision = 'dc9594c408b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('razorpay_order_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_order_razorpay_order_id'), ['razorpay_order_id'], unique=True)

    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_razorpay_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_order_number'))
        batch_op.drop_column('payment_method')
        batch_op.drop_column('razorpay_order_id')
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###
