"""Revert color_id column from ProductImage

Revision ID: dc9594c408b0
Revises: 92c647e74d56
Create Date: 2025-08-27 13:37:12.088618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9594c408b0'
down_revision = '92c647e74d56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('product_image_color_id_fkey'), type_='foreignkey')
        batch_op.drop_column('color_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('product_image_color_id_fkey'), 'color', ['color_id'], ['id'])

    # ### end Alembic commands ###
